name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP and Apache on Ubuntu
        run: |
          sudo apt-get update -y
          sudo apt-get install -y php7.4 apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2
        shell: bash

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
        working-directory: ${{ github.workspace }}

      - name: Install dependencies
        run: composer install

      - name: Configure Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
        env:
          APP_ENV: production
          APP_DEBUG: false
        working-directory: ${{ github.workspace }}

